"""ch11-b fakers

Revision ID: 09276e380192
Revises: 4491224f9539
Create Date: 2018-05-02 21:07:29.469853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09276e380192'
down_revision = '4491224f9539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_faker', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_faker', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_faker')
    op.drop_column('posts', 'is_faker')
    # ### end Alembic commands ###
